version: '3.9'

networks:
  test_network:
    driver: bridge

services:
  celery:
    build: .
    env_file:
      - .env.test
    environment:
      - DB_HOST=db_test
      - DB_PORT=5432
    command: celery --app app.celery --broker redis://redis:${REDIS_PORT}/0 --result-backend redis://redis:${REDIS_PORT}/0 worker
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - test_network

  redis:
    image: redis:7.2.4-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: --port ${REDIS_PORT}
    networks:
      - test_network

  db_test:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - test_network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - '16543:80'
    depends_on:
      - db_test
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - test_network

volumes:
  pgadmin_data:
    driver: local