version: "3.9"
services:
  db:
    image: "postgres:14-alpine"
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  db_test:
    image: "postgres:14-alpine"
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_test
    ports:
      - ${TEST_DB_PORT}:5432
    profiles:
      - dev

  app:
    image: ${IMAGE_NAME}
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 8080:8000
    depends_on:
      - db

volumes:
  db_volume:
    driver: local
