version: "3.9"
services:
  db:
    image: "postgres:14-alpine"
    restart: always
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  db_test:
    image: "postgres:14-alpine"
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_test
    ports:
      - ${TEST_DB_PORT}:5432
    profiles:
      - dev

volumes:
  db_volume:
    driver: local
