version: '3.9'

services:
  celery:
    build: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery --app=app.celery worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6380:6379

  db_test:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - ${TEST_DB_PORT}:5432

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - '16543:80'
    depends_on:
      - db_test
    volumes:
      - pgadmin_data:/var/lib/pgadmin



volumes:
  pgadmin_data:
    driver: local