name: CI/CD

on:
  push:
    branches: ["main"]

env:
  TAG: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image
        run: docker build --tag=${{ secrets.DOCKER_USERNAME }}/monika-backend:${{ env.TAG }} .
      - name: login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: publish docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/monika-backend:${{ env.TAG }}
