name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-lint.yml

  test:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-test.yml
