name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/pecuny:latest
  POETRY_VERSION: 1.7.1
  PYTHON_VERSION: 3.12

jobs:
  lint:
    uses: .github/workflows/lint.yml@main

  test:
    uses: .github/workflows/test.yml@main
