name: Lint with Pylint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Install the linter dependencies
        run: poetry install --only linter
      - name: Run pylint
        run: poetry run pylint
