name: Test

on: workflow_call
env:
  TEST_DB_NAME: test_db
  TEST_DB_PASSWORD: postgres
  TEST_DB_HOST: localhost
  TEST_DB_USER: postgres

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ inputs.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ inputs.TEST_DB_PASSWORD }}
          POSTGRES_DB: ${{ inputs.TEST_DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Init poetry
        uses: .github/workflows/reusable-poetry-run.yml
      - name: Run Tests
        run: poetry run pytest --disable-warnings -x -v
        env:
          ENVIRONMENT: "test"
          DOMAIN: "http://127.0.0.1:8000"
          SECRET_KEY: "test"
          CSRF_SECRET: "test"
          SESSION_SECRET_KEY: "test"
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          DB_NAME: ${{ inputs.TEST_DB_NAME }}
          DB_PASSWORD: ${{ inputs.TEST_DB_PASSWORD }}
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          TEST_DB_PORT: 5432
          DB_USER: ${{ inputs.TEST_DB_USER }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
